### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by mikesk8** [wavemotion-dave/XEGS-DS#3]
Hello, I have just tried your program (versions 2.8 and 2.9) with my Nintendo DS Lite (with CycleDs card) but in both cases (2 versions) I am getting back screens and nothing more. Are you able to help me? I have put in the XEGS folder the atarixl.rom too to check, but it did not help.

thank you, m.

ps. I tried 1.0 version, but its the same - black on launch :(

**Comment by wavemotion-dave** [comment]
Hey Mike - I've only ever used an R4iSCHC clone card for my DS-Lite... and it works fine. 
I also use Twilight Menu++ on my DSi with no issues.
My guess is that it can't find a file system - you might try patching via DLDI for your card but I'm guessing you may be out of luck here.
